### ISSUE TITLE
Cognate analysis not computing

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#212]
Open http://lingvodoc.ispras.ru/dictionary/1389/6/perspective/1389/7/view, Tools->Cognate analysis, "Compute" button, computation does not finish, hangs up.

Investigation shows possible problem in liboslon.so library https://github.com/ispras/lingvodoc-ext-oslon:
```
Thread 9 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc4996700 (LWP 30993)]
0x00007fffc4d23a52 in BTree::insert(BNode*) () from /usr/lib/liboslon.so
(gdb) bt
#0  0x00007fffc4d23a52 in BTree::insert(BNode*) () from /usr/lib/liboslon.so
#1  0x00007fffc4d23b28 in BTree::insert(BNode*) () from /usr/lib/liboslon.so
#2  0x00007fffc4d23b28 in BTree::insert(BNode*) () from /usr/lib/liboslon.so
#3  0x00007fffc4d23b28 in BTree::insert(BNode*) () from /usr/lib/liboslon.so
#4  0x00007fffc4d23b28 in BTree::insert(BNode*) () from /usr/lib/liboslon.so
#5  0x00007fffc4d23b28 in BTree::insert(BNode*) () from /usr/lib/liboslon.so
#6  0x00007fffc4d23b28 in BTree::insert(BNode*) () from /usr/lib/liboslon.so
#7  0x00007fffc4d28b48 in Comparison::RemoveSingleWordsInColumnsOnce() () from /usr/lib/liboslon.so
#8  0x00007fffc4d291f8 in Comparison::Process(Condition*, bool, bool) () from /usr/lib/liboslon.so
#9  0x00007fffc4d1ef84 in CognateAnalysis_GetAllOutput () from /usr/lib/liboslon.so
#10 0x00007ffff4214dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
```

Contacted Mikhail Oslon https://github.com/neoakut/.

**Comment by myrix** [comment]
With new version https://github.com/ispras/lingvodoc-ext-oslon/commit/3b1faf00cb0da65837748bbc2b784d0587fc8567 of liboslon library cognate analysis at http://lingvodoc.ispras.ru/dictionary/1389/6/perspective/1389/7/view computes succesfully.

**Comment by nadezhday** [comment]
Verified. Compute was successful.

**Comment by nadezhday** [comment]
Covered in selenium test. Dictionary of Izhma dialect of Komi-Zyrian language is used (http://83.149.198.62/).
