### ISSUE TITLE
Cognate multi-language suggestions: Compute is not successful (Error: GraphQL error: Exception)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#359]
Selenium test (test_cognate_multi_suggestions.py) - FAILed

Steps to reproduce:
Login as admin
http://83.149.198.62/dashboard/dictionaries_all
Find Dictionary of Komi-Yazva language, open lexical view
(Or just open http://83.149.198.62/dictionary/524/4/perspective/524/5/view)
Tools->Cognate multi-language suggestions
In Add language select Udmurt
Click Compute.

Expected: Analysis results

Actual: Exception 
![image](https://user-images.githubusercontent.com/59951991/95962992-c6f25280-0e0f-11eb-9031-3ed6c33d47e6.png)

data Error: GraphQL error: Exception:
Traceback (most recent call last):
  File "/api/lingvodoc/schema/query.py", line 6500, in mutate
    __intermediate_flag__))
  File "/api/lingvodoc/schema/query.py", line 5540, in perform_cognate_analysis
    group_field_id if __debug_flag__ else None))
  File "/api/lingvodoc/schema/query.py", line 4135, in parse_suggestions
    entry_id_list = list(f(*w) for w in word_list)
  File "/api/lingvodoc/schema/query.py", line 4135, in <genexpr>
    entry_id_list = list(f(*w) for w in word_list)
  File "/api/lingvodoc/schema/query.py", line 4120, in f
    ' ' + translation_str if translation_str else ''))])
KeyError: (28, 'ношна|аçсэ|ачид|мар|дан(-)|Аслаз|мар(-)ке|нош|ачыд|ачыме|ма|ти|таҗы|уно|но|си(-)|Со, со|та|сойыз|дуно|Ас, ас|ношик|со')
    at new e (vendor.1168477f.js:sourcemap:1)
    at Object.next (vendor.1168477f.js:sourcemap:1)
    at d (vendor.1168477f.js:sourcemap:1)
    at h (vendor.1168477f.js:sourcemap:1)
    at t.value (vendor.1168477f.js:sourcemap:1)
    at Object.next (vendor.1168477f.js:sourcemap:1)
    at d (vendor.1168477f.js:sourcemap:1)
    at h (vendor.1168477f.js:sourcemap:1)
    at t.value (vendor.1168477f.js:sourcemap:1)
    at vendor.1168477f.js:sourcemap:1

1) One more try. The problem is reproduced.
 
data Error: GraphQL error: Exception:
Traceback (most recent call last):
  File "/api/lingvodoc/schema/query.py", line 6500, in mutate
    __intermediate_flag__))
  File "/api/lingvodoc/schema/query.py", line 5540, in perform_cognate_analysis
    group_field_id if __debug_flag__ else None))
  File "/api/lingvodoc/schema/query.py", line 4135, in parse_suggestions
    entry_id_list = list(f(*w) for w in word_list)
  File "/api/lingvodoc/schema/query.py", line 4135, in <genexpr>
    entry_id_list = list(f(*w) for w in word_list)
  File "/api/lingvodoc/schema/query.py", line 4120, in f
    ' ' + translation_str if translation_str else ''))])
KeyError: (28, 'ношна|аçсэ|ачид|мар|дан(-)|Аслаз|мар(-)ке|нош|ачыд|ачыме|ма|ти|таҗы|уно|но|си(-)|Со, со|та|сойыз|дуно|Ас, ас|ношик|со')
    e ApolloError.js:37
    next QueryManager.js:186
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next index.js:37
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    l index.js:91
    promise callback*l/</< index.js:90
    t Observable.js:179
    value Observable.js:258
    o index.js:19
    t Observable.js:179
    value Observable.js:258
    mutate QueryManager.js:183
    mutate QueryManager.js:124
    mutate ApolloClient.js:98
    dataForChildViaMutation react-apollo.browser.umd.js:544
    value index.js:1011
    Lodash 4
    e Button.js:103
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    d raven.js:393

**Comment by nadezhday** [comment]
Run the selenium tests one more time and the problem is gone. 
Closing this issue. If the problem occurs then we will reopen this case.
