### ISSUE TITLE
Docker container server startup error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#577]
API server inside the docker container does not start, fails with following error:
```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 60, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 120, in setup
    self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=self.cfg.paste_global_conf)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/pasterapp.py", line 68, in load_pasteapp
    return loadapp(config_url, relative_to=relative_to,
  File "/usr/local/lib/python3.8/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python3.8/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python3.8/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python3.8/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python3.8/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/api/lingvodoc/__init__.py", line 1180, in main
    config.scan('.views')
  File "/usr/local/lib/python3.8/dist-packages/pyramid/config/__init__.py", line 975, in scan
    scanner.scan(package, categories=categories, onerror=onerror,
  File "/usr/local/lib/python3.8/dist-packages/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/api/lingvodoc/views/v2/phonology.py", line 49, in <module>
    import matplotlib.pyplot as pyplot
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 14, in <module>
    from .transforms import (Bbox, IdentityTransform, TransformedBbox,
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: numpy.core.multiarray failed to import
```

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified
